version: '3.4'
services:
  alfresco-alingsas-share:
    image: alfresco-share-alfresco-alingsas:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../alfresco-alingsas-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: alfresco-alingsas-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
    volumes:
      - project-code-share-classes:/usr/local/tomcat/hotswap-agent/alfresco-alingsas-share/target/classes
  alfresco-alingsas-acs:
    image: alfresco-content-services-alfresco-alingsas:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../alfresco-alingsas-platform-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - alfresco-alingsas-acs-volume:/usr/local/tomcat/alf_data
      - project-code-platform-classes:/usr/local/tomcat/hotswap-agent/alfresco-alingsas-platform/target/classes
      - project-code-platform-it-classes:/usr/local/tomcat/hotswap-agent/alfresco-alingsas-integration-tests/target/test-classes
    depends_on:
      - alfresco-alingsas-postgres
  alfresco-alingsas-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - alfresco-alingsas-db-volume:/var/lib/postgresql/data
  alfresco-alingsas-ass:
    image: alfresco/alfresco-search-services:2.0.1
    environment:
      SOLR_ALFRESCO_HOST: alfresco-alingsas-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: alfresco-alingsas-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: none
    ports:
      - "8983:8983"
    volumes:
      - alfresco-alingsas-ass-volume:/opt/alfresco-search-services/contentstore
      - alfresco-alingsas-ass-volume:/opt/alfresco-search-services/data
  transform-router:
    mem_limit: 512m
    image: quay.io/alfresco/alfresco-transform-router:1.3.1
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      ACTIVEMQ_URL: "nio://activemq:61616"
      CORE_AIO_URL : "http://transform-core-aio:8090"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - "8095:8095"
    links:
      - activemq
  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:2.3.6
    mem_limit: 1536m
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      ACTIVEMQ_URL: "nio://activemq:61616"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
      LIBREOFFICE_IS_ENABLED: "false"
    ports:
      - "8090:8090"
    links:
      - activemq
  shared-file-store:
    image: alfresco/alfresco-shared-file-store:0.10.0
    mem_limit: 512m
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      scheduler.content.age.millis: 86400000
      scheduler.cleanup.interval: 86400000
    ports:
      - "8099:8099"
    volumes:
      - shared-file-store-volume:/tmp/Alfresco/sfs
  activemq:
    image: alfresco/alfresco-activemq:5.15.8
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP

volumes:
  alfresco-alingsas-acs-volume:
    external: true
  alfresco-alingsas-db-volume:
    external: true
  alfresco-alingsas-ass-volume:
    external: true
  shared-file-store-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
  project-code-share-classes:
  project-code-share-pa-classes:
  project-code-platform-classes:
  project-code-platform-it-classes:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    project-code-share-classes:
      alpha: "../../../alfresco-alingsas-share/target/classes"
      beta: "volume://project-code-share-classes"
      mode: "two-way-resolved"
    project-code-platform-classes:
      alpha: "../../../alfresco-alingsas-platform/target/classes"
      beta: "volume://project-code-platform-classes"
      mode: "two-way-resolved"
    project-code-platform-it-classes:
      alpha: "../../../alfresco-alingsas-integration-tests/target/test-classes"
      beta: "volume://project-code-platform-it-classes"
      mode: "two-way-resolved"