version: '3.4'
services:
  alfresco-alingsas-share:
    image: alfresco-share-alfresco-alingsas:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../alfresco-alingsas-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: alfresco-alingsas-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  alfresco-alingsas-acs:
    image: alfresco-content-services-alfresco-alingsas:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../alfresco-alingsas-platform-docker/target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      JAVA_OPTS: "
        -Dmessaging.broker.url=\"failover:(nio://alfresco-alingsas-activemq:61616)?timeout=3000&jms.useCompression=true\"
        "
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - alfresco-alingsas-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - alfresco-alingsas-postgres
  alfresco-alingsas-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - alfresco-alingsas-db-volume:/var/lib/postgresql/data
  alfresco-alingsas-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: alfresco-alingsas-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: alfresco-alingsas-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - alfresco-alingsas-ass-volume:/opt/alfresco-search-services/contentstore
      - alfresco-alingsas-ass-volume:/opt/alfresco-search-services/data
  transform-router:
    image: quay.io/alfresco/alfresco-transform-router:1.3.1
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      ACTIVEMQ_URL: "nio://activemq:61616"
      CORE_AIO_URL: "http://transform-core-aio:8090"
      IMAGEMAGICK_URL: "http://imagemagick:8090"
      PDF_RENDERER_URL: "http://alfresco-pdf-renderer:8090"
      LIBREOFFICE_URL: "http://libreoffice:8090"
      TIKA_URL: "http://tika:8090"
      MISC_URL: "http://misc:8090"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - "8095:8095"
    links:
      - activemq
  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:2.3.6
    environment:
      JAVA_OPTS: " -Xms256m -Xmx1536m"
      ACTIVEMQ_URL: "nio://activemq:61616"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
      LIBREOFFICE_IS_ENABLED: "false"
    ports:
      - "8090:8090"
    links:
      - activemq
  shared-file-store:
    image: alfresco/alfresco-shared-file-store:0.8.0
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      scheduler.content.age.millis: 86400000
      scheduler.cleanup.interval: 86400000
    ports:
      - "8099:8099"
    volumes:
      - shared-file-store-volume:/tmp/Alfresco/sfs
  activemq:
      image: alfresco/alfresco-activemq:5.16.1
      mem_limit: 1g
      ports:
        - 8161:8161 # Web Console
        - 5672:5672 # AMQP
        - 61616:61616 # OpenWire
        - 61613:61613 # STOMP

volumes:
  alfresco-alingsas-acs-volume:
    external: true
  alfresco-alingsas-db-volume:
    external: true
  alfresco-alingsas-ass-volume:
    external: true
  shared-file-store-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
